name: Deploy App

on:
  workflow_run:
    workflows: ["Docker Image Build & Push"]
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    env:
      DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKER_TAG: ${{ github.sha }}

    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          cat <<EOF > .env
          DOCKERHUB_USER=${{ vars.DOCKERHUB_USERNAME }}
          DOCKER_TAG=${{ github.sha }}

          ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}

          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}

          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}

          CLIENT_URL=${{ vars.CLIENT_URL }}
          NODE_ENV=production
          EOF      

      - name: Deploy with docker compose
        run: docker compose down && docker compose up -d --force-recreate --pull always

      - name: Remove unused images
        run: docker image prune -af
