name: CI Pipeline

on:
    push:
        branches: [main]        
    workflow_dispatch: 

jobs:
    getting_short_sha:
        runs-on: ubuntu-latest
        outputs:
            short_sha: ${{ steps.vars.outputs.short_sha }}
        steps:
            - name: Generating Short SHA
              id: vars
              run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    build_and_test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            node_version: 20
            run_tests: true

    docker_image:
        uses: ./.github/workflows/reusable-docker.yml
        needs: [build_and_test , getting_short_sha]
        with:
            image_name: "mishra0703/ecommerce-fullstack-webapp"
            tags: |
                mishra0703/ecommerce-fullstack-webapp:latest
                mishra0703/ecommerce-fullstack-webapp:sha-${{ needs.getting_short_sha.outputs.short_sha }}
        secrets: 
            Dockerhub_Username: ${{ vars.DOCKERHUB_USERNAME }}
            Dockerhub_Token: ${{ secrets.DOCKERHUB_TOKEN }}


    deploy:
        runs-on: ubuntu-latest        
        needs: [docker_image]
        environment: production
        steps:
            - name: Deploying Webapp
              run: echo "Deploying image --> ${{ needs.docker_image.outputs.image_url }} to production"
